# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5e57fe9d682c92b36f9155013b2e4981"
organization_id = "40808029"
name = "SAP Sync"
application_url = "https://lt-sap-sync.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "metaobjects/update", "metaobjects/create" ]
  uri = "/webhooks/sap/feed"
  filter = "type:sap_feed"

  [[webhooks.subscriptions]]
  topics = ["metaobjects/update"]
  uri = "/webhooks/shopify/definition/update"
  filter = "type:brand OR type:category OR type:occasion"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_metaobjects, write_inventory, read_metaobject_definitions, write_files, read_locations, write_metaobjects, write_metaobject_definitions"

[auth]
redirect_urls = [ 
  "https://lt-sap-sync.onrender.com/auth/callback",
  "https://lt-sap-sync.onrender.com/auth/shopify/callback",
  "https://lt-sap-sync.onrender.com/api/auth/callback"
]
