[[extensions]]
name = "Sync All Products"
handle = "sync-all-products"
type = "flow_action"
uid = "d0ed8260-bc7d-4bfc-9110-dae06d3241df"
description = "Gather all current products in shop, sync their data with SAP & run AI Analysis on products with new images."
runtime_url = "https://fo-ft-corner-hanging.trycloudflare.com/api/sync"
schema = "./schema.graphql"
return_type_ref = "Warnings"

[settings]

  [[settings.fields]]
  type = "boolean"
  key = "forceAI"
  name = "Force AI Re-Analysis"
  description = "Rerun the AI analysis on all products, regardless of image update."
  required = true
